Add redux
v-mikhailov/ToDo pull request #1
Opened 2020-10-26 19:26 UTC by v-mikhailov

2020-10-27 09:09 UTC, anasvikh requested changes

2020-10-27 09:09 UTC, anasvikh commented on src/Redux/tasksReducer.ts
> +      // как сделать оптимальнее?
А что тебе тут не нравится?
Можно поменять логику определения типа, чтобы не делать это вручную
У тебя же есть массив типов, можно инкрементить id и получать следующее значение

С точки зрения ux, лучше дать пользователю самому выбирать новый тип, чтобы у него была возможность пропускать какие-то стадии, или, например, возвращать таск в работу
Как вариант, можно добавить выпадающий список доступных типов на карточку таска и перемещать таск при выборе

2020-11-02 08:52 UTC, anasvikh requested changes

2020-11-02 08:52 UTC, anasvikh commented on src/Redux/acion.ts
> +export const deleteTask = (task: TaskInterface): ColumnActionInterfaces => {
Можно же сразу передавать сюда taskId

2020-11-05 10:30 UTC, anasvikh requested changes

2020-11-05 10:30 UTC, anasvikh commented on src/Componets/TaskPopup.tsx
> +        fullTask.isOpen && (
А почему так, а не в open?

2020-11-05 10:30 UTC, anasvikh commented on src/Componets/NewTaskForm.tsx
> +          <AccordionDetails className={styles.formBlock}>
Есть подозрение, что неправильно используешь AccordionDetails. Почему их несколько внутри одного Accordion? И почему они расположены внутри form?

2020-11-05 21:44 UTC, v-mikhailov commented on src/Componets/TaskPopup.tsx
> +        fullTask.isOpen && (
Чтобы пустой диалог точно не рендерился.

2020-11-06 09:17 UTC, anasvikh approved these changes

2020-11-08 19:08 UTC, merged