Router
v-mikhailov/ToDo pull request #3
Opened 2020-11-09 01:20 UTC by v-mikhailov

2020-11-18 00:00 UTC, Eyara requested changes

2020-11-18 00:00 UTC, Eyara commented on src/Componets/ListColumn.tsx
> +  columns: any,
типизация потерялась из-за коннекта и мап стейта в пропсы? в идеале сделать как тут:
https://medium.com/knerd/typescript-tips-series-proper-typing-of-react-redux-connected-components-eda058b6727d
Но не критикал, можно и забить пока

2020-11-19 14:49 UTC, v-mikhailov commented on src/App.tsx
> +                  <Desk deskId={desk.id}/>
Как обойтись без стейта в Desk? Мне нужен deskId, чтобы рендерить нужные колонки и таски в зависимости от выбранной доски.

2020-11-19 14:53 UTC, v-mikhailov commented on src/Componets/ListColumn.tsx
> +  // const columns = useSelector((state: RootState) => state.columns.columns);
Если исправить нейминг, то будет другая ошибка.

2020-11-24 13:20 UTC, Eyara commented on package-lock.json
> -{
не надо его удалять(

2020-11-24 13:20 UTC, Eyara commented on src/App.tsx
> +                  <Desk deskId={desk.id}/>
Ну смотри. Тебе там нужен id и name у desk'a. DeskId ты прокидываешь отсюда пропсом.
Потом ты идёшь в стейт, получаешь **все** desks, фильтруешь по Id, который прокинул и выбираешь name.
При этом больше никак стейт в Desk компоненте не юзается. Ты можешь сделать тож самое, но на уровне выше (в app), и тогда desk'у не нужен будет стейт, т.к. он из пропсов будет получать всю сущность, с Id и Name'ом

2020-11-26 15:15 UTC, anasvikh requested changes

2020-11-26 15:15 UTC, anasvikh commented on src/Redux/API/dishesReducer.ts
> +// почему с интерфейсом появляются ошибки?
Какие именно ошибки? Потому что у интерфейса и объекта разный набор полей? И почему у certainDish вместо типа или хотя бы any пустой объект?

2020-11-26 15:15 UTC, anasvikh commented on src/Componets/API/DishCard.tsx
> +      dishes.map((dish: any) => {
А почему any?

2020-11-30 13:06 UTC, anasvikh requested changes

2020-11-30 13:06 UTC, anasvikh commented on src/Redux/API/apiAction.ts
> +            ingridients
А какой смысл передавать весь meal + отдельно еще ингридиенты?
Можно же создать на основе ответа от бэка новый объект, в котором будут только используемые поля + ingridients, являющийся массивом ингридиентов

2020-12-01 11:21 UTC, anasvikh requested changes

2020-12-01 11:21 UTC, anasvikh commented on src/Redux/API/dishesReducer.ts
> +  certainDish: any,
а certainDish это не DishInterface разве у тебя?

2020-12-01 11:21 UTC, anasvikh commented on src/Componets/API/DishCard.tsx
> +      dishes.map((dish: any) => {
Так и осталось any
Хотя тоже похоже на DishInterface

2020-12-01 12:49 UTC, merged